apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simpleapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/looselycoupled/gitops
    targetRevision: HEAD
    path: charts/simpleapp
    helm:
      valueFiles:
      - ../../environments/testubg.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: example
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
